# Generated by Django 4.2.26 on 2025-11-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_remove_perfildueno_nombre_comercial_and_more"),
        ("complejos", "0006_complejo_pais_complejo_provincia"),
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservaFija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        help_text="0=Lunes, 6=Domingo",
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Primera fecha en que se aplicará esta reserva fija"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Aprobación"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True,
                        help_text="Motivo por el cual el dueño rechazó la reserva fija",
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "aprobada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_fijas_aprobadas",
                        to="cuentas.perfildueno",
                    ),
                ),
                (
                    "cancha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_fijas",
                        to="complejos.cancha",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_fijas",
                        to="cuentas.perfiljugador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva Fija",
                "verbose_name_plural": "Reservas Fijas",
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("cancha", "dia_semana", "hora_inicio")},
            },
        ),
    ]
