# Generated by Django 4.2.26 on 2025-11-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_remove_perfildueno_nombre_comercial_and_more"),
        ("reservas", "0002_reservafija"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservafija",
            name="aprobada_por",
        ),
        migrations.RemoveField(
            model_name="reservafija",
            name="fecha_aprobacion",
        ),
        migrations.RemoveField(
            model_name="reservafija",
            name="motivo_rechazo",
        ),
        migrations.AddField(
            model_name="reservafija",
            name="creada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas_fijas_creadas",
                to="cuentas.perfildueno",
            ),
        ),
        migrations.AlterField(
            model_name="reservafija",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVA", "Activa"), ("CANCELADA", "Cancelada")],
                default="ACTIVA",
                max_length=20,
            ),
        ),
    ]
