# Generated by Django 4.2.26 on 2025-11-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfildueno",
            name="nombre_comercial",
        ),
        migrations.RemoveField(
            model_name="perfiljugador",
            name="puntos_ranking",
        ),
        migrations.RemoveField(
            model_name="perfiljugador",
            name="total_partidos",
        ),
        migrations.RemoveField(
            model_name="perfiljugador",
            name="total_torneos",
        ),
        migrations.AddField(
            model_name="perfildueno",
            name="cuit_cuil",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="perfildueno",
            name="nombre_negocio",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="perfiljugador",
            name="partidos_jugados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="perfiljugador",
            name="perfil_publico",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="perfiljugador",
            name="pie_habil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DERECHO", "Derecho"),
                    ("IZQUIERDO", "Izquierdo"),
                    ("AMBOS", "Ambos"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="perfiljugador",
            name="posicion_favorita",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="perfiljugador",
            name="rating",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="perfiljugador",
            name="torneos_ganados",
            field=models.IntegerField(default=0),
        ),
    ]
