# Generated by Django 4.2.26 on 2025-11-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.CharField(choices=[('PADEL', 'Pádel'), ('FUTBOL5', 'Fútbol 5'), ('FUTBOL7', 'Fútbol 7'), ('FUTBOL11', 'Fútbol 11'), ('TENIS', 'Tenis'), ('FUTBOL_TENIS', 'Fútbol-Tenis'), ('BASQUET', 'Básquet'), ('VOLEY', 'Voley')], max_length=20)),
                ('tipo_superficie', models.CharField(blank=True, max_length=100)),
                ('techada', models.BooleanField(default=False)),
                ('iluminacion', models.BooleanField(default=False)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base por turno', max_digits=10)),
                ('duracion_turno_minutos', models.IntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['complejo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=300)),
                ('localidad', models.CharField(max_length=200)),
                ('latitud', models.FloatField(help_text='Coordenada latitud WGS84 para búsquedas y mapas')),
                ('longitud', models.FloatField(help_text='Coordenada longitud WGS84 para búsquedas y mapas')),
                ('google_place_id', models.CharField(blank=True, max_length=200)),
                ('direccion_formateada', models.CharField(blank=True, help_text='Dirección tal como la devuelve Google Places API', max_length=400)),
                ('google_maps_url', models.URLField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('subdominio', models.CharField(help_text='Ej: puntoyreves para puntoyreves.dereves.ar', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='complejos/logos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complejo',
                'verbose_name_plural': 'Complejos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioComplejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('BUFET', 'Bufet'), ('PARRILLA', 'Parrilla'), ('AGUA_CALIENTE', 'Agua Caliente'), ('WIFI', 'Wi-Fi'), ('SALON', 'Salón'), ('ESTACIONAMIENTO', 'Estacionamiento'), ('VESTUARIOS', 'Vestuarios'), ('QUINCHO', 'Quincho')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='complejos.complejo')),
            ],
            options={
                'verbose_name': 'Servicio de Complejo',
                'verbose_name_plural': 'Servicios de Complejos',
            },
        ),
    ]
