# Generated by Django 5.2.8 on 2025-11-21 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=300)),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(default='Córdoba', max_length=100)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('latitud', models.FloatField(help_text='Coordenada latitud WGS84 para búsquedas y mapas')),
                ('longitud', models.FloatField(help_text='Coordenada longitud WGS84 para búsquedas y mapas')),
                ('google_place_id', models.CharField(blank=True, max_length=200)),
                ('direccion_formateada', models.CharField(blank=True, help_text='Dirección tal como la devuelve Google Places API', max_length=400)),
                ('google_maps_url', models.URLField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('subdominio', models.CharField(blank=True, help_text='Se genera automáticamente. Ej: puntoyreves para puntoyreves.dereves.ar', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='complejos/logos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complejos', to='cuentas.perfildueno')),
            ],
            options={
                'verbose_name': 'Complejo',
                'verbose_name_plural': 'Complejos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_superficie', models.CharField(blank=True, max_length=100)),
                ('tipo_pared', models.CharField(blank=True, choices=[('VIDRIO', 'Vidrio'), ('CEMENTO', 'Cemento'), ('LADRILLO', 'Ladrillo'), ('MALLA', 'Malla Metálica'), ('MIXTA', 'Mixta (Vidrio y Cemento)'), ('PANORAMICA', 'Panorámica (Todo Vidrio)'), ('ALAMBRADO', 'Alambrado'), ('SIN_PARED', 'Sin Paredes / Cancha Abierta')], help_text='Tipo de pared/cerramiento de la cancha', max_length=20)),
                ('techada', models.BooleanField(default=False)),
                ('iluminacion', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='canchas/')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base por turno', max_digits=10)),
                ('precio_hora', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por hora', max_digits=10, null=True)),
                ('horario_apertura', models.TimeField(default='08:00')),
                ('horario_cierre', models.TimeField(default='23:00')),
                ('duracion_turno_minutos', models.IntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canchas', to='cuentas.deporte', verbose_name='Deporte')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='complejos.complejo')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['complejo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('aprobada', models.BooleanField(default=True, help_text='Si está aprobada para uso público')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agregada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades_agregadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['provincia', 'nombre'],
                'unique_together': {('nombre', 'provincia', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='ServicioComplejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('BUFET', 'Bufet'), ('PARRILLA', 'Parrilla'), ('AGUA_CALIENTE', 'Agua Caliente'), ('WIFI', 'Wi-Fi'), ('SALON', 'Salón'), ('ESTACIONAMIENTO', 'Estacionamiento'), ('VESTUARIOS', 'Vestuarios'), ('QUINCHO', 'Quincho')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='complejos.complejo')),
            ],
            options={
                'verbose_name': 'Servicio de Complejo',
                'verbose_name_plural': 'Servicios de Complejos',
                'unique_together': {('complejo', 'tipo_servicio')},
            },
        ),
    ]
