# Generated by Django 4.2.26 on 2025-11-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('complejos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejo',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complejos', to='cuentas.perfildueno'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='complejos.complejo'),
        ),
        migrations.AlterUniqueTogether(
            name='serviciocomplejo',
            unique_together={('complejo', 'tipo_servicio')},
        ),
    ]
