# Generated by Django 4.2.26 on 2025-11-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complejos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancha",
            name="horario_apertura",
            field=models.TimeField(default="08:00"),
        ),
        migrations.AddField(
            model_name="cancha",
            name="horario_cierre",
            field=models.TimeField(default="23:00"),
        ),
        migrations.AddField(
            model_name="cancha",
            name="precio_hora",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio por hora",
                max_digits=10,
                null=True,
            ),
        ),
    ]
