# Generated by Django 4.2.26 on 2025-11-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0003_cancha_horario_apertura_cancha_horario_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='canchas/'),
        ),
    ]
