# Generated by Django 4.2.26 on 2025-11-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complejos", "0004_cancha_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancha",
            name="tipo_pared",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIDRIO", "Vidrio"),
                    ("CEMENTO", "Cemento"),
                    ("LADRILLO", "Ladrillo"),
                    ("MALLA", "Malla Metálica"),
                    ("MIXTA", "Mixta (Vidrio y Cemento)"),
                    ("PANORAMICA", "Panorámica (Todo Vidrio)"),
                    ("ALAMBRADO", "Alambrado"),
                    ("SIN_PARED", "Sin Paredes / Cancha Abierta"),
                ],
                help_text="Tipo de pared/cerramiento de la cancha",
                max_length=20,
            ),
        ),
    ]
