# Generated by Django 4.2.26 on 2025-11-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complejos", "0005_cancha_tipo_pared"),
    ]

    operations = [
        migrations.AddField(
            model_name="complejo",
            name="pais",
            field=models.CharField(default="Argentina", max_length=100),
        ),
        migrations.AddField(
            model_name="complejo",
            name="provincia",
            field=models.CharField(default="Córdoba", max_length=100),
        ),
    ]
