# Generated by Django 4.2.3 on 2025-11-11 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complejos", "0006_complejo_pais_complejo_provincia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("provincia", models.CharField(max_length=100)),
                ("pais", models.CharField(default="Argentina", max_length=100)),
                (
                    "aprobada",
                    models.BooleanField(
                        default=True, help_text="Si está aprobada para uso público"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "agregada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="localidades_agregadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "ordering": ["provincia", "nombre"],
                "unique_together": {("nombre", "provincia", "pais")},
            },
        ),
    ]
