# Generated by Django 4.2.3 on 2025-11-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("complejos", "0007_localidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoComplejo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="complejos/fotos/")),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "orden",
                    models.IntegerField(default=0, help_text="Orden de visualización"),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Marca si esta es la foto principal del complejo",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "complejo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="complejos.complejo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de Complejo",
                "verbose_name_plural": "Fotos de Complejos",
                "ordering": ["complejo", "-es_principal", "orden", "-creado_en"],
            },
        ),
    ]
