# Generated by Django 4.2.3 on 2025-11-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complejos", "0008_fotocomplejo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FotoComplejo",
        ),
    ]
