# Generated by Django 4.2.3 on 2025-11-11 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("complejos", "0008_fotocomplejo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservas", "0003_remove_reservafija_aprobada_por_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("GASTO", "Gasto")],
                        max_length=10,
                    ),
                ),
                ("categoria", models.CharField(max_length=20)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        help_text="Foto o PDF del comprobante",
                        null=True,
                        upload_to="finanzas/comprobantes/",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "complejo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="complejos.complejo",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones",
                        to="reservas.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ResumenMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "total_ingresos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_gastos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ingresos_reservas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ingresos_reservas_fijas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ingresos_otros",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cantidad_reservas", models.IntegerField(default=0)),
                ("cantidad_transacciones", models.IntegerField(default=0)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "complejo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumenes_mensuales",
                        to="complejos.complejo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen Mensual",
                "verbose_name_plural": "Resúmenes Mensuales",
                "ordering": ["-año", "-mes"],
                "unique_together": {("complejo", "año", "mes")},
            },
        ),
    ]
